import type { VideoContent } from './types';

export const PRELOADED_VIDEOS: VideoContent[] = [
  {
    id: 'X9otDixAtFw',
    title: 'What Is Something? – The Biggest Question of Philosophy & Physics',
    thumbnail: 'https://i.ytimg.com/vi/X9otDixAtFw/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=X9otDixAtFw',
    channelTitle: 'Kurzgesagt – In a Nutshell',
    channelThumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_k-3253sZNEV_0N2e7g5bM93H5_Ev-3-8n2a_g14Q=s176-c-k-c0x00ffffff-no-rj',
    duration: '15:33',
    viewCount: '23M views',
    publishedAt: '1 year ago',
  },
  {
    id: 'Yocja_N5s1I',
    title: 'The Agricultural Revolution: Crash Course World History #1',
    thumbnail: 'https://i.ytimg.com/vi/Yocja_N5s1I/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=Yocja_N5s1I',
    channelTitle: 'CrashCourse',
    channelThumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_kH--IuJ7a_3A6I13-4I5-x2n5X2BEsm03LSS340g=s176-c-k-c0x00ffffff-no-rj',
    duration: '11:17',
    viewCount: '13M views',
    publishedAt: '12 years ago',
  },
  {
    id: 'aircAruvnKk',
    title: 'But what is a neural network? | Chapter 1, Deep learning',
    thumbnail: 'https://i.ytimg.com/vi/aircAruvnKk/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    channelTitle: '3Blue1Brown',
    channelThumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_lGFbN-2Q2592-p7s_28o-aC-S_u-gMM-I9r4S3Aw=s176-c-k-c0x00ffffff-no-rj',
    duration: '19:13',
    viewCount: '20M views',
    publishedAt: '7 years ago',
  },
  {
    id: 'rfscVS0vtbw',
    title: 'Learn Python - Full Course for Beginners [Tutorial]',
    thumbnail: 'https://i.ytimg.com/vi/rfscVS0vtbw/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    channelTitle: 'freeCodeCamp.org',
    channelThumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_k_33wI-k10b-3O--2dc-nJd-i_01_f5-x2_Fh5Tw=s176-c-k-c0x00ffffff-no-rj',
    duration: '4:26:52',
    viewCount: '62M views',
    publishedAt: '5 years ago',
  },
  {
    id: 'p66-4oY_s0g',
    title: 'The myth of Cupid and Psyche - Brendan Pelsue',
    thumbnail: 'https://i.ytimg.com/vi/p66-4oY_s0g/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=p66-4oY_s0g',
    channelTitle: 'TED-Ed',
    channelThumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_nF_dYw73-k3_ynL-4l8iszp5lq-h-pUss_4I-a=s176-c-k-c0x00ffffff-no-rj',
    duration: '4:51',
    viewCount: '11M views',
    publishedAt: '6 years ago',
  },
  {
    id: 'r9PeYPHdpNo',
    title: 'Go inside the world of whales in this stunning documentary',
    thumbnail: 'https://i.ytimg.com/vi/r9PeYPHdpNo/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=r9PeYPHdpNo',
    channelTitle: 'National Geographic',
    channelThumbnail: 'https://yt3.googleusercontent.com/ytc/AIdro_k8jG_3kP-Vq8Z-Gmu-4v36_5z4c-l2_A-B_A=s176-c-k-c0x00ffffff-no-rj',
    duration: '48:54',
    viewCount: '4.8M views',
    publishedAt: '2 years ago',
  },
  {
    id: '9lDCYjb8RHk',
    title: 'How to draw a face',
    thumbnail: 'https://i.ytimg.com/vi/9lDCYjb8RHk/sddefault.jpg',
    source: 'youtube',
    url: 'https://www.youtube.com/watch?v=9lDCYjb8RHk',
    channelTitle: 'Proko',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AKedOLR-4hZ7V8heC4mSp-c2Uqg-83rFlXw1262d-4GqCw=s88-c-k-c0x00ffffff-no-rj',
    duration: '26:30',
    viewCount: '7.3M views',
    publishedAt: '4 years ago',
  }
];